name: check-and-build

on:
  pull_request:

env:
  GO111MODULE: on

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.1'

      - uses: actions/setup-node@v3
        with:
          node-version: 11.11.0
          cache: yarn
          cache-dependency-path: ui/yarn.lock

      - run: mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
          version: v3.95

      - run: make download-tools

      - run: docker version

      - run: make install

      - run: make generate
      - run: make lint
      - run: make test
      - run: make build-js

      - run: bash <(curl -s https://codecov.io/bash)
